---
- synchronize: src=../ dest=/home/pi/homeautomation recursive=yes
- pip: name=python-mpd2
- pip: name=rxv
- pip: name=redis
- pip: name=requests
- file: name=/home/pi/homeautomation/alarm_clock/alarm_clock.py mode=755
- file: name=/home/pi/homeautomation/alarm_clock/phone_detection.py mode=755
- file: name=/home/pi/homeautomation/alarm_clock/lights_off.py mode=755
- cron: name="phone_detection" minute="*" job="/home/pi/homeautomation/alarm_clock/phone_detection.py"
- cron: name="lights_off" minute="*" job="/home/pi/homeautomation/alarm_clock/lights_off.py"
- name: Adding alarms
  with_items:
    - day: 1
      hour: "{{ weekdays.hour }}"
      minute: "{{ weekdays.minute }}"
    - day: 2
      hour: "{{ weekdays.hour }}"
      minute: "{{ weekdays.minute }}"
    - day: 3
      hour: "{{ weekdays.hour }}"
      minute: "{{ weekdays.minute }}"
    - day: 4
      hour: "{{ weekdays.hour }}"
      minute: "{{ weekdays.minute }}"
    - day: 5
      hour: "{{ weekdays.hour }}"
      minute: "{{ weekdays.minute }}"
    - day: 6
      hour: "{{ saturday['hour'] }}"
      minute: "{{ saturday['minute'] }}"
    - day: 7
      hour: "{{ sunday['hour'] }}"
      minute: "{{ sunday['minute'] }}"
  cron: name="alarm_clock weekday {{ item.day }}"
        weekday="{{ item.day }}"
        hour="{{ item.hour }}"
        minute="{{ item.minute }}"
        job="/home/pi/homeautomation/alarm_clock/alarm_clock.py --playlist=\"{{ playlist }}\" --sleep=\"{{ sleep }}\""
