---
- name: install pip3
  pip: name=pip executable=pip3 state=latest

- name: install homeassistant
  pip: name=homeassistant executable=pip3

- name: create an user
  user: name="homeassistant"
        comment="Home Assistant user"
        createhome=yes

- template: src=home-assistant.service.j2 dest=/etc/systemd/system/home-assistant.service mode=0644
  register: service

- template: src=configuration.yaml.j2 dest=/home/homeassistant/.homeassistant/configuration.yaml mode=0644 owner=homeassistant group=homeassistant
  register: configuration

- name: reload systemd
  command: systemctl daemon-reload
  when: service.changed

- name: restart homeassistant
  service: name=home-assistant state=restarted
  when: configuration.changed

# - name: start home-assistant
#   service: name=homeassistant@home-assistant
#            state=running
#            enabled=yes