---
 - lineinfile: dest=/etc/modules regexp="ipv6" line="ipv6"
   notify: ipv6
 - apt_key: url=http://apt.mopidy.com/mopidy.gpg state=present
 - apt_repository: repo='deb http://apt.mopidy.com/ stable main contrib non-free' state=present
 - apt_repository: repo='deb-src http://apt.mopidy.com/ stable main contrib non-free' state=present
 - apt: name=mopidy update_cache=yes
 - with_items:
     - libspotify12
     - libspotify-dev
   apt: name=$item
 - template: src=asound.conf.j2 dest=/etc/asound.conf
 - git: repo=https://github.com/woutervanwijk/Mopidy-Webclient.git dest=/home/pi/Mopidy-Webclient
 - git: repo=https://github.com/dz0ny/mopidy-lux.git dest=/home/pi/mopidy-lux
   sudo: False
 - file: dest=/home/pi/.config/mopidy/ state=directory owner=pi group=pi
 - template: src=mopidy.conf.j2 dest=/home/pi/.config/mopidy/mopidy.conf
   sudo: False
 - with_items:
     - pyspotify
     - Mopidy-Spotify
     - Mopidy-SoundCloud
   pip: name=$item
 - pip: name=/home/pi/homeautomation/mopidy-rxv
 - template: src=mopidy.conf.supervisor.j2 dest=/etc/supervisor/conf.d/mopidy.conf
   notify: mopidy

